// Static mapping of NFL team codes to logo image paths in /public/images/teams
// Plug & play: replace each placeholder SVG/PNG in public/images/teams with the real logo, keep the same filename.
// You can switch extensions (e.g. to .svg) without code changes IF you also rename here.
export const TEAM_LOGOS: Record<string, string> = {
  ARI: '/images/teams/ARI.svg',
  ATL: '/images/teams/ATL.svg',
  BAL: '/images/teams/BAL.svg',
  BUF: '/images/teams/BUF.svg',
  CAR: '/images/teams/CAR.svg',
  CHI: '/images/teams/CHI.svg',
  CIN: '/images/teams/CIN.svg',
  CLE: '/images/teams/CLE.svg',
  DAL: '/images/teams/DAL.svg',
  DEN: '/images/teams/DEN.svg',
  DET: '/images/teams/DET.svg',
  GB:  '/images/teams/GB.svg',
  HOU: '/images/teams/HOU.svg',
  IND: '/images/teams/IND.svg',
  JAX: '/images/teams/JAX.svg',
  KC:  '/images/teams/KC.svg',
  LV:  '/images/teams/LV.svg',
  LAC: '/images/teams/LAC.svg',
  LAR: '/images/teams/LAR.svg',
  MIA: '/images/teams/MIA.svg',
  MIN: '/images/teams/MIN.svg',
  NE:  '/images/teams/NE.svg',
  NO:  '/images/teams/NO.svg',
  NYG: '/images/teams/NYG.svg',
  NYJ: '/images/teams/NYJ.svg',
  PHI: '/images/teams/PHI.svg',
  PIT: '/images/teams/PIT.svg',
  SF:  '/images/teams/SF.svg',
  SEA: '/images/teams/SEA.svg',
  TB:  '/images/teams/TB.svg',
  TEN: '/images/teams/TEN.svg',
  WAS: '/images/teams/WAS.svg',
};
