// Static mapping of NFL team codes to logo image paths in /public/images/teams
// Plug & play: replace each placeholder SVG/PNG in public/images/teams with the real logo, keep the same filename.
// You can switch extensions (e.g. to .svg) without code changes IF you also rename here.
export const TEAM_LOGOS: Record<string, string> = {
  ARI: '/images/teams/ARI.svg',
  ATL: '/images/teams/ATL.svg',
  BAL: '/images/teams/BAL.svg',
  BUF: '/images/teams/BUF.svg',
  CAR: '/images/teams/CAR.svg',
  CHI: '/images/teams/CHI.svg',
  CIN: '/images/teams/CIN.svg',
  CLE: '/images/teams/CLE.svg',
  DAL: '/images/teams/DAL.svg',
  DEN: '/images/teams/DEN.svg',
  DET: '/images/teams/DET.svg',
  GB:  '/images/teams/GB.svg',
  HOU: '/images/teams/HOU.svg',
  IND: '/images/teams/IND.svg',
  JAX: '/images/teams/JAX.svg',
  KC:  '/images/teams/KC.svg',
  LV:  '/images/teams/LV.svg',
  LAC: '/images/teams/LAC.svg',
  LAR: '/images/teams/LAR.svg',
  MIA: '/images/teams/MIA.svg',
  MIN: '/images/teams/MIN.svg',
  NE:  '/images/teams/NE.svg',
  NO:  '/images/teams/NO.svg',
  NYG: '/images/teams/NYG.svg',
  NYJ: '/images/teams/NYJ.svg',
  PHI: '/images/teams/PHI.svg',
  PIT: '/images/teams/PIT.svg',
  SF:  '/images/teams/SF.svg',
  SEA: '/images/teams/SEA.svg',
  TB:  '/images/teams/TB.svg',
  TEN: '/images/teams/TEN.svg',
  WAS: '/images/teams/WAS.svg',
};

// Primary brand or helmet dominant color (approx). Used for UI accents.
export const TEAM_COLORS: Record<string, string> = {
  ARI: '#97233F',
  ATL: '#A71930',
  BAL: '#241773',
  BUF: '#00338D',
  CAR: '#0085CA',
  CHI: '#0B162A',
  CIN: '#FB4F14',
  CLE: '#311D00',
  DAL: '#002244',
  DEN: '#FB4F14',
  DET: '#0076B6',
  GB:  '#203731',
  HOU: '#03202F',
  IND: '#002C5F',
  JAX: '#006778',
  KC:  '#E31837',
  LV:  '#000000',
  LAC: '#0080C6',
  LAR: '#003594',
  MIA: '#008E97',
  MIN: '#4F2683',
  NE:  '#002244',
  NO:  '#101820',
  NYG: '#0B2265',
  NYJ: '#125740',
  PHI: '#004C54',
  PIT: '#FFB612',
  SF:  '#AA0000',
  SEA: '#002244',
  TB:  '#D50A0A',
  TEN: '#0C2340',
  WAS: '#5A1414',
};
