// Static mapping of NFL team codes to logo image paths in /public/images/teams
// Plug & play: replace each placeholder SVG/PNG in public/images/teams with the real logo, keep the same filename.
// You can switch extensions (e.g. to .svg) without code changes IF you also rename here.
export const TEAM_LOGOS: Record<string, string> = {
  ARI: '/images/teams/ARI.png',
  ATL: '/images/teams/ATL.png',
  BAL: '/images/teams/BAL.png',
  BUF: '/images/teams/BUF.png',
  CAR: '/images/teams/CAR.png',
  CHI: '/images/teams/CHI.png',
  CIN: '/images/teams/CIN.png',
  CLE: '/images/teams/CLE.png',
  DAL: '/images/teams/DAL.png',
  DEN: '/images/teams/DEN.png',
  DET: '/images/teams/DET.png',
  GB:  '/images/teams/GB.png',
  HOU: '/images/teams/HOU.png',
  IND: '/images/teams/IND.png',
  JAX: '/images/teams/JAX.png',
  KC:  '/images/teams/KC.png',
  LV:  '/images/teams/LV.png',
  LAC: '/images/teams/LAC.png',
  LAR: '/images/teams/LAR.png',
  MIA: '/images/teams/MIA.png',
  MIN: '/images/teams/MIN.png',
  NE:  '/images/teams/NE.png',
  NO:  '/images/teams/NO.png',
  NYG: '/images/teams/NYG.png',
  NYJ: '/images/teams/NYJ.png',
  PHI: '/images/teams/PHI.png',
  PIT: '/images/teams/PIT.png',
  SF:  '/images/teams/SF.png',
  SEA: '/images/teams/SEA.png',
  TB:  '/images/teams/TB.png',
  TEN: '/images/teams/TEN.png',
  WAS: '/images/teams/WAS.png',
};

// Primary brand or helmet dominant color (approx). Used for UI accents.
export const TEAM_COLORS: Record<string, string> = {
  ARI: '#97233F',
  ATL: '#A71930',
  BAL: '#241773',
  BUF: '#00338D',
  CAR: '#0085CA',
  CHI: '#0B162A',
  CIN: '#FB4F14',
  CLE: '#311D00',
  DAL: '#002244',
  DEN: '#FB4F14',
  DET: '#0076B6',
  GB:  '#203731',
  HOU: '#03202F',
  IND: '#002C5F',
  JAX: '#006778',
  KC:  '#E31837',
  LV:  '#000000',
  LAC: '#0080C6',
  LAR: '#003594',
  MIA: '#008E97',
  MIN: '#4F2683',
  NE:  '#002244',
  NO:  '#101820',
  NYG: '#0B2265',
  NYJ: '#125740',
  PHI: '#004C54',
  PIT: '#FFB612',
  SF:  '#AA0000',
  SEA: '#002244',
  TB:  '#D50A0A',
  TEN: '#0C2340',
  WAS: '#5A1414',
};
