import { Metadata } from 'next'
import { SEOData, SanityImageWithUrl } from '@/types'
import { generateAutoSeo } from './auto-seo-generator'

interface ExtendedSEOData extends SEOData {
  autoGenerate?: boolean
  focusKeyword?: string
  additionalKeywords?: string[]
}

export interface ContentData {
  title: string
  summary?: string
  slug: {
    current: string
  }
  seo?: SEOData
  coverImage?: SanityImageWithUrl
  author?: {
    name: string
  }
  date?: string
  category?: {
    title: string
    seo?: SEOData
  }
}

export function generateSEOMetadata(
  content: ContentData,
  basePath: string = '',
  baseUrl: string = 'https://thegamesnap.com'
): Metadata {
  const {
    title,
    summary,
    slug,
    seo,
    coverImage,
    author,
    date,
    category,
  } = content

  const extendedSeo: ExtendedSEOData | undefined = seo as ExtendedSEOData | undefined
  const autoGenerated = extendedSeo?.autoGenerate ? generateAutoSeo({
    title,
    summary,
    categoryTitle: category?.title,
    existing: extendedSeo
  }) : undefined

  const metaTitle = extendedSeo?.metaTitle || autoGenerated?.metaTitle || title
  const metaDescription = extendedSeo?.metaDescription || autoGenerated?.metaDescription || summary || `Read the latest NFL news and updates about ${title} on The Snap.`
  const ogTitle = extendedSeo?.ogTitle || autoGenerated?.ogTitle || metaTitle
  const ogDescription = extendedSeo?.ogDescription || autoGenerated?.ogDescription || metaDescription
  const ogImageUrl = extendedSeo?.ogImage?.asset?.url || coverImage?.asset?.url || '/images/thesnap-logo-new copy.jpg'
  const canonicalUrl = extendedSeo?.canonicalUrl || `${baseUrl}${basePath}/${slug.current}`

  // Build keywords array
  const keywords = [
    extendedSeo?.focusKeyword || autoGenerated?.focusKeyword,
    ...((extendedSeo?.additionalKeywords) || (autoGenerated?.additionalKeywords) || []),
    'NFL news',
    'NFL headlines',
    'NFL updates',
    'The Snap',
    category?.title && `NFL ${category.title}`,
    author?.name && `${author.name} NFL`,
  ].filter(Boolean) as string[]

  const metadata: Metadata = {
    title: metaTitle,
    description: metaDescription,
    keywords: keywords.join(', '),
    authors: author?.name ? [{ name: author.name }] : undefined,
    openGraph: {
      title: ogTitle,
      description: ogDescription,
      url: canonicalUrl,
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: ogTitle,
        },
      ],
      type: 'article',
      publishedTime: date,
      authors: author?.name ? [author.name] : undefined,
      section: category?.title,
    },
    twitter: {
      card: 'summary_large_image',
      title: ogTitle,
      description: ogDescription,
      images: [ogImageUrl],
    },
    alternates: {
      canonical: canonicalUrl,
    },
    robots: {
      index: !extendedSeo?.noIndex,
      follow: !extendedSeo?.noIndex,
      googleBot: {
        index: !extendedSeo?.noIndex,
        follow: !extendedSeo?.noIndex,
      },
    },
  }

  return metadata
}

export function generateCategorySEOMetadata(
  category: {
    title: string
    description?: string
    slug: {
      current: string
    }
    seo?: SEOData
  },
  baseUrl: string = 'https://thegamesnap.com'
): Metadata {
  const {
    title,
    description,
    slug,
    seo,
  } = category

  const extendedSeo: ExtendedSEOData | undefined = seo as ExtendedSEOData | undefined
  const autoGenerated = extendedSeo?.autoGenerate ? generateAutoSeo({
    title,
    summary: description,
    categoryTitle: title,
    existing: extendedSeo
  }) : undefined

  const metaTitle = extendedSeo?.metaTitle || autoGenerated?.metaTitle || `${title} - NFL News & Updates | The Snap`
  const metaDescription = extendedSeo?.metaDescription || autoGenerated?.metaDescription || description || `Get the latest NFL ${title.toLowerCase()} news, updates, and analysis on The Snap.`
  const ogImageUrl = extendedSeo?.ogImage?.asset?.url || '/images/thesnap-logo-new copy.jpg'
  const canonicalUrl = `${baseUrl}/categories/${slug.current}`

  const keywords = [
    extendedSeo?.focusKeyword || autoGenerated?.focusKeyword,
    ...((extendedSeo?.additionalKeywords) || (autoGenerated?.additionalKeywords) || []),
    `NFL ${title}`,
    `NFL ${title} news`,
    `NFL ${title} updates`,
    'The Snap',
    'NFL news',
  ].filter(Boolean) as string[]

  const metadata: Metadata = {
    title: metaTitle,
    description: metaDescription,
    keywords: keywords.join(', '),
    openGraph: {
      title: metaTitle,
      description: metaDescription,
      url: canonicalUrl,
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: metaTitle,
        },
      ],
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: metaTitle,
      description: metaDescription,
      images: [ogImageUrl],
    },
    alternates: {
      canonical: canonicalUrl,
    },
    robots: {
      index: !extendedSeo?.noIndex,
      follow: !extendedSeo?.noIndex,
      googleBot: {
        index: !extendedSeo?.noIndex,
        follow: !extendedSeo?.noIndex,
      },
    },
  }

  return metadata
}
